include_guard()

if (NOT CMAKE_BUILD_TYPE)
    message(STATUS "Using Debug configuration as none has been specified")
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type")
elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
    message(STATUS "Using Debug configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
    message(STATUS "Using Release configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    message(STATUS "Using RelWithDebInfo configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
    message(STATUS "Using MinSizeRel configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "Asan")
    message(STATUS "Using ASAN configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "Ubsan")
    message(STATUS "Using UBSAN configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "Tsan")
    message(STATUS "Using TSAN configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "Stan")
    message(STATUS "Using STAN configuration")
elseif(CMAKE_BUILD_TYPE STREQUAL "Coverage")
    message(STATUS "Using Coverage configuration")
else()
    message(FATAL "Unknown configuration type: ${CMAKE_BUILD_TYPE}")
endif()