//
// Created by raiden on 07/09/2019.
//

#ifndef NEURALNETWORKS_BATCHEDSTOCHASTICGRADIENTDESCENT_H
#define NEURALNETWORKS_BATCHEDSTOCHASTICGRADIENTDESCENT_H

#endif //NEURALNETWORKS_BATCHEDSTOCHASTICGRADIENTDESCENT_H
